Algoritmo "nome e idade"

Var
nome1, nome2 : caractere
idade1, idade2, media : real



Inicio
Escreval("Dados da Primeira pessoa: ")
escreva("Nome: ")
Leia(nome1)
Escreva("Idade: ")
Leia(idade1)

Escreval("Dados da Segunda pessoa: ")
escreva("Nome: ")
Leia(nome2)
Escreva("Idade: ")
Leia(idade2)

Media <- (idade1 + idade2) /2

Escreval("A idade media de", nome1, "e", nome2, "é de", media, "anos" )





Fimalgoritmo