Algoritmo "Retangulo"

Var

base, altura, area, perimetro, diagonal : real




Inicio

Escreva("Base do retangulo: ")
leia(base)
Escreva("Altura do retangulo: ")
leia(altura)

area <- base * altura
perimetro <- 2* base + 2* altura
diagonal <-  RaizQ(Exp(base, 2)+Exp(altura, 2))

Escreval("AREA = ", area:8:4)
escreval("PERIMETRO = ", perimetro:8:4)
Escreval("DIAGONAL = ", diagonal:8:4)

fimalgoritmo





fimse
fimalgoritmo




Fimalgoritmo