Algoritmo "semnome"

Var

  idade : inteiro
  salario1, salario2 : real
  nome : caractere

Inicio

  escreval("Digite seu nome: ")
  leia(nome)
  escreval("Digite sua idade: ")
  leia(idade)
  escreval("Difite quanto voce ganhou nos dois ultimos meses: ")
  leia(salario1)
  leia(salario2)
  
  escreval("Dados DIGITADOS:")
  escreval("Nome = ", nome)
  escreval("Idade = ", idade)
  escreval("salario 1 = ", salario1:8:2)
  escreval("salario 2 = ", salario2:8:2)



Fimalgoritmo